# Generated by Django 2.1.2 on 2019-01-11 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estadoCivil',
            field=models.CharField(choices=[('s', 'Soltero'), ('e', 'Sin especificar'), ('c', 'Casado'), ('d', 'Divorciado')], max_length=15),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='tipoCuenta',
            field=models.CharField(choices=[('corriente', 'Corriente'), ('ahorros', 'Ahorro'), ('basica', 'Básica'), ('nomina', 'Nómina'), ('valores', 'Valores'), ('juvenil', 'Juvenil'), ('programado', 'Ahorro Programado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('retiro', 'Retiro'), ('deposito', 'Depósito'), ('transferencia', 'Transferencia')], max_length=30),
        ),
    ]
