# Generated by Django 2.1.2 on 2019-01-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0002_auto_20190110_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estadoCivil',
            field=models.CharField(choices=[('e', 'Sin especificar'), ('s', 'Soltero'), ('c', 'Casado'), ('d', 'Divorciado')], max_length=15),
        ),
    ]
