# Generated by Django 2.1.2 on 2019-01-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0003_auto_20190111_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estadoCivil',
            field=models.CharField(choices=[('s', 'Soltero'), ('c', 'Casado'), ('e', 'Sin especificar'), ('d', 'Divorciado')], max_length=15),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='tipoCuenta',
            field=models.CharField(choices=[('corriente', 'Corriente'), ('ahorros', 'Ahorro'), ('basica', 'Básica'), ('juvenil', 'Juvenil')], max_length=30),
        ),
    ]
