# Generated by Django 2.1.2 on 2019-01-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0006_auto_20190115_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='cuenta_destino',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estadoCivil',
            field=models.CharField(choices=[('e', 'Sin especificar'), ('d', 'Divorciado'), ('c', 'Casado'), ('s', 'Soltero')], max_length=15),
        ),
    ]
